# Config File
output_folder: "experiments"
experiment_name: "test3"

workers: 4
img_size: 416

model:
  anchors:
    - [10, 13]
    - [16, 30]
    - [33, 23]
    - [30, 61]
    - [62, 45]
    - [59, 119]
    - [116, 90]
    - [156, 198]
    - [373, 326]

train:
  dir: "path to images"
  annotation_file: "path to coco annotation file"
  val_dir: ~
  val_annotation_file: ~
  val_split: 0.2
  normalized: false
  output_name: "yolov3_xray.pt"

  epochs: 100
  gradient_accumulations: 1
  batch_size: 8
  pretrained_weights: "yolov3/pretrained_weights/yolov3-openimages.weights"
  checkpoint_interval: 5
  evaluation_interval: 1
  augment: false
  compute_map: false  # if True computes mAP every tenth batch
  multiscale_training: true # allow for multi-scale training
  iou_thres: 0.5
  nms_thres: 0.5
  conf_thres: 0.5

  optimizer:
    # Possible values for type: "adam, sgd"
    type: "sgd"
    lr: 0.001
    momentum: 0.9  # Only for SGD
    decay: 0.005
    scheduler_milestones:
      - 50
      - 70
    gamma: 0.1

test:
  weights_file: "experiments/test3/weights/yolov3_xray.pt"
  dir: "data/xray/test/images"
  annotation_file: "data/xray/test/coco_test.json"
  batch_size: 2
  normalized: false
  iou_thres: 0.5
  nms_thres: 0.4
  conf_thres: 0.8
  json_file_output: "experiments/test3/test_output.json"

inference:
  weights_file: "experiments/test3/weights/yolov3_xray.pt"
  dir: "data/xray/test/images"
  batch_size: 8
  output: "experiments/test3/inference"
  max_images: -1 # Number of maximum images to infer. If -1, infers all from inference directory
  classes:
    - firearm
    - firearmparts
    - knife

  nms_thres: 0.4
  conf_thres: 0.8

visdom:
  show: true
  host: 'localhost'
  port: 8097
