# Config File
output_folder: "experiments"
experiment_name: "db4_test"
views:
  - A
  - B
  - C
  - D

workers: 4
img_size: 544

model:
  anchors:
    - [10, 13]
    - [16, 30]
    - [33, 23]
    - [30, 61]
    - [62, 45]
    - [59, 119]
    - [116, 90]
    - [156, 198]
    - [373, 326]

train:
  dir: "PATH TO IMAGES DIR"
  annotation_file: "PATH TO ANNOTATIONS FILE"
  val_dir: ~
  val_annotation_file: ~
  val_split: 0.2
  normalized: false
  output_name: "yolov3_xray.pt"

  epochs: 100
  gradient_accumulations: 1
  batch_size: 10
  pretrained_weights: "PATH TO PRETRAINED WEIGHTS"
  checkpoint_interval: 5
  evaluation_interval: 1
  augment: true
  compute_map: false  # if True computes mAP every tenth batch
  multiscale_training: true # allow for multi-scale training
  iou_thres: 0.5
  nms_thres: 0.5
  conf_thres: 0.5

  optimizer:
    # Possible values for type: "adam, sgd"
    type: "adam"
    lr: 0.0001
    momentum: 0.9  # Only for SGD
    decay: 0.00005
    scheduler_milestones:
      - 30
      - 40
    gamma: 0.1

test:
  weights_file: "PATH TO WEIGHTS FILE"
  dir: "PATH TO IMAGES DIR"
  annotation_file: "PATH TO ANNOTATION FILE"
  batch_size: 6
  normalized: false
  iou_thres: 0.5
  nms_thres: 0.4
  conf_thres: 0.5
  p_value: 0.95
  json_file_output: "yolov3_xray_sv.json"

inference:
  weights_file:  "PATH TO WEIGHTS FILE"
  dir: "PATH TO IMAGES DIR"
  annotation_file: "PATH TO ANNOTATIONS FILE"
  normalized: false
  with_gt: true
  batch_size: 8
  max_images: -1 # Number of maximum images to infer. If -1, infers all from inference directory
  classes:
    - firearm
    - laptop
    - knife
    - camera
  nms_thres: 0.4
  conf_thres: 0.5
  p_value: 0.95
  save_structured: false

visdom:
  show: true
  host: 'localhost'
  port: 8097
